/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as CaptureThoughtRouteImport } from './routes/capture.thought'
import { Route as CaptureTaskRouteImport } from './routes/capture.task'
import { Route as CaptureReminderRouteImport } from './routes/capture.reminder'
import { Route as CaptureNoteRouteImport } from './routes/capture.note'
import { Route as CaptureEventRouteImport } from './routes/capture.event'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as TabsTasksRouteImport } from './routes/_tabs.tasks'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsCalendarRouteImport } from './routes/_tabs.calendar'
import { Route as TabsAiRouteImport } from './routes/_tabs.ai'
import { Route as TasksIdEditRouteImport } from './routes/tasks.$id.edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureThoughtRoute = CaptureThoughtRouteImport.update({
  id: '/capture/thought',
  path: '/capture/thought',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureTaskRoute = CaptureTaskRouteImport.update({
  id: '/capture/task',
  path: '/capture/task',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureReminderRoute = CaptureReminderRouteImport.update({
  id: '/capture/reminder',
  path: '/capture/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureNoteRoute = CaptureNoteRouteImport.update({
  id: '/capture/note',
  path: '/capture/note',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureEventRoute = CaptureEventRouteImport.update({
  id: '/capture/event',
  path: '/capture/event',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsTasksRoute = TabsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCalendarRoute = TabsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAiRoute = TabsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => TabsRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/ai': typeof TabsAiRoute
  '/calendar': typeof TabsCalendarRoute
  '/home': typeof TabsHomeRoute
  '/profile': typeof TabsProfileRoute
  '/tasks': typeof TabsTasksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/capture/event': typeof CaptureEventRoute
  '/capture/note': typeof CaptureNoteRoute
  '/capture/reminder': typeof CaptureReminderRoute
  '/capture/task': typeof CaptureTaskRoute
  '/capture/thought': typeof CaptureThoughtRoute
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/ai': typeof TabsAiRoute
  '/calendar': typeof TabsCalendarRoute
  '/home': typeof TabsHomeRoute
  '/profile': typeof TabsProfileRoute
  '/tasks': typeof TabsTasksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/capture/event': typeof CaptureEventRoute
  '/capture/note': typeof CaptureNoteRoute
  '/capture/reminder': typeof CaptureReminderRoute
  '/capture/task': typeof CaptureTaskRoute
  '/capture/thought': typeof CaptureThoughtRoute
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/_tabs/ai': typeof TabsAiRoute
  '/_tabs/calendar': typeof TabsCalendarRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/tasks': typeof TabsTasksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/capture/event': typeof CaptureEventRoute
  '/capture/note': typeof CaptureNoteRoute
  '/capture/reminder': typeof CaptureReminderRoute
  '/capture/task': typeof CaptureTaskRoute
  '/capture/thought': typeof CaptureThoughtRoute
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/$id/edit': typeof TasksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/onboarding'
    | '/ai'
    | '/calendar'
    | '/home'
    | '/profile'
    | '/tasks'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/capture/event'
    | '/capture/note'
    | '/capture/reminder'
    | '/capture/task'
    | '/capture/thought'
    | '/tasks/$id'
    | '/tasks/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/onboarding'
    | '/ai'
    | '/calendar'
    | '/home'
    | '/profile'
    | '/tasks'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/capture/event'
    | '/capture/note'
    | '/capture/reminder'
    | '/capture/task'
    | '/capture/thought'
    | '/tasks/$id'
    | '/tasks/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/notifications'
    | '/onboarding'
    | '/_tabs/ai'
    | '/_tabs/calendar'
    | '/_tabs/home'
    | '/_tabs/profile'
    | '/_tabs/tasks'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/capture/event'
    | '/capture/note'
    | '/capture/reminder'
    | '/capture/task'
    | '/capture/thought'
    | '/tasks/$id'
    | '/tasks/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  CaptureEventRoute: typeof CaptureEventRoute
  CaptureNoteRoute: typeof CaptureNoteRoute
  CaptureReminderRoute: typeof CaptureReminderRoute
  CaptureTaskRoute: typeof CaptureTaskRoute
  CaptureThoughtRoute: typeof CaptureThoughtRoute
  TasksIdRoute: typeof TasksIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/thought': {
      id: '/capture/thought'
      path: '/capture/thought'
      fullPath: '/capture/thought'
      preLoaderRoute: typeof CaptureThoughtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/task': {
      id: '/capture/task'
      path: '/capture/task'
      fullPath: '/capture/task'
      preLoaderRoute: typeof CaptureTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/reminder': {
      id: '/capture/reminder'
      path: '/capture/reminder'
      fullPath: '/capture/reminder'
      preLoaderRoute: typeof CaptureReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/note': {
      id: '/capture/note'
      path: '/capture/note'
      fullPath: '/capture/note'
      preLoaderRoute: typeof CaptureNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/event': {
      id: '/capture/event'
      path: '/capture/event'
      fullPath: '/capture/event'
      preLoaderRoute: typeof CaptureEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/tasks': {
      id: '/_tabs/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TabsTasksRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/calendar': {
      id: '/_tabs/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof TabsCalendarRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/ai': {
      id: '/_tabs/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof TabsAiRouteImport
      parentRoute: typeof TabsRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof TasksIdRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAiRoute: typeof TabsAiRoute
  TabsCalendarRoute: typeof TabsCalendarRoute
  TabsHomeRoute: typeof TabsHomeRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsTasksRoute: typeof TabsTasksRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAiRoute: TabsAiRoute,
  TabsCalendarRoute: TabsCalendarRoute,
  TabsHomeRoute: TabsHomeRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsTasksRoute: TabsTasksRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

interface TasksIdRouteChildren {
  TasksIdEditRoute: typeof TasksIdEditRoute
}

const TasksIdRouteChildren: TasksIdRouteChildren = {
  TasksIdEditRoute: TasksIdEditRoute,
}

const TasksIdRouteWithChildren =
  TasksIdRoute._addFileChildren(TasksIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  CaptureEventRoute: CaptureEventRoute,
  CaptureNoteRoute: CaptureNoteRoute,
  CaptureReminderRoute: CaptureReminderRoute,
  CaptureTaskRoute: CaptureTaskRoute,
  CaptureThoughtRoute: CaptureThoughtRoute,
  TasksIdRoute: TasksIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
