/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AiMemoryRouteImport } from './routes/ai-memory'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtsIdRouteImport } from './routes/thoughts.$id'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as RemindersIdRouteImport } from './routes/reminders.$id'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CaptureThoughtRouteImport } from './routes/capture.thought'
import { Route as CaptureTaskRouteImport } from './routes/capture.task'
import { Route as CaptureReminderRouteImport } from './routes/capture.reminder'
import { Route as CaptureNoteRouteImport } from './routes/capture.note'
import { Route as CaptureEventRouteImport } from './routes/capture.event'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TabsTasksRouteImport } from './routes/_tabs.tasks'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsHomeRouteImport } from './routes/_tabs.home'
import { Route as TabsCalendarRouteImport } from './routes/_tabs.calendar'
import { Route as TabsAiRouteImport } from './routes/_tabs.ai'
import { Route as ThoughtsIdEditRouteImport } from './routes/thoughts.$id.edit'
import { Route as TasksIdEditRouteImport } from './routes/tasks.$id.edit'
import { Route as RemindersIdEditRouteImport } from './routes/reminders.$id.edit'
import { Route as NotesIdEditRouteImport } from './routes/notes.$id.edit'
import { Route as EventsIdEditRouteImport } from './routes/events.$id.edit'

const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMemoryRoute = AiMemoryRouteImport.update({
  id: '/ai-memory',
  path: '/ai-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsIdRoute = ThoughtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ThoughtsRoute,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIdRoute = RemindersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RemindersRoute,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotesRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const CaptureThoughtRoute = CaptureThoughtRouteImport.update({
  id: '/capture/thought',
  path: '/capture/thought',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureTaskRoute = CaptureTaskRouteImport.update({
  id: '/capture/task',
  path: '/capture/task',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureReminderRoute = CaptureReminderRouteImport.update({
  id: '/capture/reminder',
  path: '/capture/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureNoteRoute = CaptureNoteRouteImport.update({
  id: '/capture/note',
  path: '/capture/note',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureEventRoute = CaptureEventRouteImport.update({
  id: '/capture/event',
  path: '/capture/event',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsTasksRoute = TabsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsHomeRoute = TabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCalendarRoute = TabsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAiRoute = TabsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => TabsRoute,
} as any)
const ThoughtsIdEditRoute = ThoughtsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ThoughtsIdRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TasksIdRoute,
} as any)
const RemindersIdEditRoute = RemindersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RemindersIdRoute,
} as any)
const NotesIdEditRoute = NotesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NotesIdRoute,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-memory': typeof AiMemoryRoute
  '/events': typeof EventsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reminders': typeof RemindersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/ai': typeof TabsAiRoute
  '/calendar': typeof TabsCalendarRoute
  '/home': typeof TabsHomeRoute
  '/profile': typeof TabsProfileRoute
  '/tasks': typeof TabsTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/capture/event': typeof CaptureEventRoute
  '/capture/note': typeof CaptureNoteRoute
  '/capture/reminder': typeof CaptureReminderRoute
  '/capture/task': typeof CaptureTaskRoute
  '/capture/thought': typeof CaptureThoughtRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/thoughts/$id': typeof ThoughtsIdRouteWithChildren
  '/events/$id/edit': typeof EventsIdEditRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/reminders/$id/edit': typeof RemindersIdEditRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/thoughts/$id/edit': typeof ThoughtsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-memory': typeof AiMemoryRoute
  '/events': typeof EventsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reminders': typeof RemindersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/ai': typeof TabsAiRoute
  '/calendar': typeof TabsCalendarRoute
  '/home': typeof TabsHomeRoute
  '/profile': typeof TabsProfileRoute
  '/tasks': typeof TabsTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/capture/event': typeof CaptureEventRoute
  '/capture/note': typeof CaptureNoteRoute
  '/capture/reminder': typeof CaptureReminderRoute
  '/capture/task': typeof CaptureTaskRoute
  '/capture/thought': typeof CaptureThoughtRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/thoughts/$id': typeof ThoughtsIdRouteWithChildren
  '/events/$id/edit': typeof EventsIdEditRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/reminders/$id/edit': typeof RemindersIdEditRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/thoughts/$id/edit': typeof ThoughtsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/ai-memory': typeof AiMemoryRoute
  '/events': typeof EventsRouteWithChildren
  '/insights': typeof InsightsRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reminders': typeof RemindersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/thoughts': typeof ThoughtsRouteWithChildren
  '/_tabs/ai': typeof TabsAiRoute
  '/_tabs/calendar': typeof TabsCalendarRoute
  '/_tabs/home': typeof TabsHomeRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/tasks': typeof TabsTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/capture/event': typeof CaptureEventRoute
  '/capture/note': typeof CaptureNoteRoute
  '/capture/reminder': typeof CaptureReminderRoute
  '/capture/task': typeof CaptureTaskRoute
  '/capture/thought': typeof CaptureThoughtRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/reminders/$id': typeof RemindersIdRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/thoughts/$id': typeof ThoughtsIdRouteWithChildren
  '/events/$id/edit': typeof EventsIdEditRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
  '/reminders/$id/edit': typeof RemindersIdEditRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/thoughts/$id/edit': typeof ThoughtsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-memory'
    | '/events'
    | '/insights'
    | '/notes'
    | '/notifications'
    | '/onboarding'
    | '/reminders'
    | '/settings'
    | '/thoughts'
    | '/ai'
    | '/calendar'
    | '/home'
    | '/profile'
    | '/tasks'
    | '/api/chat'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/capture/event'
    | '/capture/note'
    | '/capture/reminder'
    | '/capture/task'
    | '/capture/thought'
    | '/events/$id'
    | '/notes/$id'
    | '/reminders/$id'
    | '/tasks/$id'
    | '/thoughts/$id'
    | '/events/$id/edit'
    | '/notes/$id/edit'
    | '/reminders/$id/edit'
    | '/tasks/$id/edit'
    | '/thoughts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-memory'
    | '/events'
    | '/insights'
    | '/notes'
    | '/notifications'
    | '/onboarding'
    | '/reminders'
    | '/settings'
    | '/thoughts'
    | '/ai'
    | '/calendar'
    | '/home'
    | '/profile'
    | '/tasks'
    | '/api/chat'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/capture/event'
    | '/capture/note'
    | '/capture/reminder'
    | '/capture/task'
    | '/capture/thought'
    | '/events/$id'
    | '/notes/$id'
    | '/reminders/$id'
    | '/tasks/$id'
    | '/thoughts/$id'
    | '/events/$id/edit'
    | '/notes/$id/edit'
    | '/reminders/$id/edit'
    | '/tasks/$id/edit'
    | '/thoughts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/ai-memory'
    | '/events'
    | '/insights'
    | '/notes'
    | '/notifications'
    | '/onboarding'
    | '/reminders'
    | '/settings'
    | '/thoughts'
    | '/_tabs/ai'
    | '/_tabs/calendar'
    | '/_tabs/home'
    | '/_tabs/profile'
    | '/_tabs/tasks'
    | '/api/chat'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/capture/event'
    | '/capture/note'
    | '/capture/reminder'
    | '/capture/task'
    | '/capture/thought'
    | '/events/$id'
    | '/notes/$id'
    | '/reminders/$id'
    | '/tasks/$id'
    | '/thoughts/$id'
    | '/events/$id/edit'
    | '/notes/$id/edit'
    | '/reminders/$id/edit'
    | '/tasks/$id/edit'
    | '/thoughts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AiMemoryRoute: typeof AiMemoryRoute
  EventsRoute: typeof EventsRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  NotesRoute: typeof NotesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  RemindersRoute: typeof RemindersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ThoughtsRoute: typeof ThoughtsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  CaptureEventRoute: typeof CaptureEventRoute
  CaptureNoteRoute: typeof CaptureNoteRoute
  CaptureReminderRoute: typeof CaptureReminderRoute
  CaptureTaskRoute: typeof CaptureTaskRoute
  CaptureThoughtRoute: typeof CaptureThoughtRoute
  TasksIdRoute: typeof TasksIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-memory': {
      id: '/ai-memory'
      path: '/ai-memory'
      fullPath: '/ai-memory'
      preLoaderRoute: typeof AiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/$id': {
      id: '/thoughts/$id'
      path: '/$id'
      fullPath: '/thoughts/$id'
      preLoaderRoute: typeof ThoughtsIdRouteImport
      parentRoute: typeof ThoughtsRoute
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/$id': {
      id: '/reminders/$id'
      path: '/$id'
      fullPath: '/reminders/$id'
      preLoaderRoute: typeof RemindersIdRouteImport
      parentRoute: typeof RemindersRoute
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/capture/thought': {
      id: '/capture/thought'
      path: '/capture/thought'
      fullPath: '/capture/thought'
      preLoaderRoute: typeof CaptureThoughtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/task': {
      id: '/capture/task'
      path: '/capture/task'
      fullPath: '/capture/task'
      preLoaderRoute: typeof CaptureTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/reminder': {
      id: '/capture/reminder'
      path: '/capture/reminder'
      fullPath: '/capture/reminder'
      preLoaderRoute: typeof CaptureReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/note': {
      id: '/capture/note'
      path: '/capture/note'
      fullPath: '/capture/note'
      preLoaderRoute: typeof CaptureNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/event': {
      id: '/capture/event'
      path: '/capture/event'
      fullPath: '/capture/event'
      preLoaderRoute: typeof CaptureEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/tasks': {
      id: '/_tabs/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TabsTasksRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/home': {
      id: '/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabsHomeRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/calendar': {
      id: '/_tabs/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof TabsCalendarRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/ai': {
      id: '/_tabs/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof TabsAiRouteImport
      parentRoute: typeof TabsRoute
    }
    '/thoughts/$id/edit': {
      id: '/thoughts/$id/edit'
      path: '/edit'
      fullPath: '/thoughts/$id/edit'
      preLoaderRoute: typeof ThoughtsIdEditRouteImport
      parentRoute: typeof ThoughtsIdRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof TasksIdRoute
    }
    '/reminders/$id/edit': {
      id: '/reminders/$id/edit'
      path: '/edit'
      fullPath: '/reminders/$id/edit'
      preLoaderRoute: typeof RemindersIdEditRouteImport
      parentRoute: typeof RemindersIdRoute
    }
    '/notes/$id/edit': {
      id: '/notes/$id/edit'
      path: '/edit'
      fullPath: '/notes/$id/edit'
      preLoaderRoute: typeof NotesIdEditRouteImport
      parentRoute: typeof NotesIdRoute
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAiRoute: typeof TabsAiRoute
  TabsCalendarRoute: typeof TabsCalendarRoute
  TabsHomeRoute: typeof TabsHomeRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsTasksRoute: typeof TabsTasksRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAiRoute: TabsAiRoute,
  TabsCalendarRoute: TabsCalendarRoute,
  TabsHomeRoute: TabsHomeRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsTasksRoute: TabsTasksRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

interface EventsIdRouteChildren {
  EventsIdEditRoute: typeof EventsIdEditRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdEditRoute: EventsIdEditRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRouteWithChildren
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRouteWithChildren,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface NotesIdRouteChildren {
  NotesIdEditRoute: typeof NotesIdEditRoute
}

const NotesIdRouteChildren: NotesIdRouteChildren = {
  NotesIdEditRoute: NotesIdEditRoute,
}

const NotesIdRouteWithChildren =
  NotesIdRoute._addFileChildren(NotesIdRouteChildren)

interface NotesRouteChildren {
  NotesIdRoute: typeof NotesIdRouteWithChildren
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesIdRoute: NotesIdRouteWithChildren,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface RemindersIdRouteChildren {
  RemindersIdEditRoute: typeof RemindersIdEditRoute
}

const RemindersIdRouteChildren: RemindersIdRouteChildren = {
  RemindersIdEditRoute: RemindersIdEditRoute,
}

const RemindersIdRouteWithChildren = RemindersIdRoute._addFileChildren(
  RemindersIdRouteChildren,
)

interface RemindersRouteChildren {
  RemindersIdRoute: typeof RemindersIdRouteWithChildren
}

const RemindersRouteChildren: RemindersRouteChildren = {
  RemindersIdRoute: RemindersIdRouteWithChildren,
}

const RemindersRouteWithChildren = RemindersRoute._addFileChildren(
  RemindersRouteChildren,
)

interface ThoughtsIdRouteChildren {
  ThoughtsIdEditRoute: typeof ThoughtsIdEditRoute
}

const ThoughtsIdRouteChildren: ThoughtsIdRouteChildren = {
  ThoughtsIdEditRoute: ThoughtsIdEditRoute,
}

const ThoughtsIdRouteWithChildren = ThoughtsIdRoute._addFileChildren(
  ThoughtsIdRouteChildren,
)

interface ThoughtsRouteChildren {
  ThoughtsIdRoute: typeof ThoughtsIdRouteWithChildren
}

const ThoughtsRouteChildren: ThoughtsRouteChildren = {
  ThoughtsIdRoute: ThoughtsIdRouteWithChildren,
}

const ThoughtsRouteWithChildren = ThoughtsRoute._addFileChildren(
  ThoughtsRouteChildren,
)

interface TasksIdRouteChildren {
  TasksIdEditRoute: typeof TasksIdEditRoute
}

const TasksIdRouteChildren: TasksIdRouteChildren = {
  TasksIdEditRoute: TasksIdEditRoute,
}

const TasksIdRouteWithChildren =
  TasksIdRoute._addFileChildren(TasksIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AiMemoryRoute: AiMemoryRoute,
  EventsRoute: EventsRouteWithChildren,
  InsightsRoute: InsightsRoute,
  NotesRoute: NotesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  RemindersRoute: RemindersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ThoughtsRoute: ThoughtsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  CaptureEventRoute: CaptureEventRoute,
  CaptureNoteRoute: CaptureNoteRoute,
  CaptureReminderRoute: CaptureReminderRoute,
  CaptureTaskRoute: CaptureTaskRoute,
  CaptureThoughtRoute: CaptureThoughtRoute,
  TasksIdRoute: TasksIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
